# Generated by Django 4.0.5 on 2022-06-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='information',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
