# Generated by Django 4.0.5 on 2022-06-12 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='street_address',
            new_name='city',
        ),
    ]
