# Generated by Django 4.0.5 on 2022-06-12 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address_type',
        ),
    ]
