# Generated by Django 4.0.5 on 2022-06-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_remove_address_address_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='card',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(to='shop.product'),
        ),
    ]
