# Generated by Django 4.0.5 on 2022-06-13 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_remove_order_card_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.brand'),
        ),
    ]
