# Generated by Django 4.0.5 on 2022-06-13 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_color_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='brand',
        ),
    ]
