# Generated by Django 4.0.5 on 2022-06-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_remove_color_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='card',
            field=models.ManyToManyField(to='shop.card'),
        ),
    ]
