# Generated by Django 3.2.5 on 2022-06-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_order_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='card',
            field=models.ManyToManyField(to='shop.Order_Item'),
        ),
    ]
