# Generated by Django 3.2.5 on 2022-06-19 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_alter_order_card'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='card',
            new_name='order_item',
        ),
    ]
